//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.01 at 03:55:57 PM BST 
//

package uk.org.radmee.whereisrobbie.xml.gpx;


import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Default;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

@Root(name = "gpx", strict = false)
@Default
public class Gpx
{

    @Element(required=false)
    protected String		name;
    @Element(required=false)
    protected String		desc;
    @Element(required=false)
    protected String		author;
    @Element(required=false)
    protected String		email;
    @Element(required=false)
    protected String		url;
    @Element(required=false)
    protected String		urlname;
	@Element(required=false)
	protected String			time;
	@Element(required=false)
    protected String		keywords;
	@Element(required=false)
    protected BoundsType	bounds;
	@ElementList(required=false)
	protected List<Gpx.Wpt>	wpt;
	@ElementList(required=false)
	protected List<Gpx.Rte>	rte;
	@ElementList(inline=true,required=false)
	protected List<Gpx.Trk>	trk;
	@Attribute(required = true)
	protected String		version;
	@Attribute(required = true)
	protected String		creator;

	public String getName()
	{
		return name;
	}

	public void setName(String value)
	{
		this.name = value;
	}

	public String getDesc()
	{
		return desc;
	}

	public void setDesc(String value)
	{
		this.desc = value;
	}

	public String getAuthor()
	{
		return author;
	}

	public void setAuthor(String value)
	{
		this.author = value;
	}

	public String getEmail()
	{
		return email;
	}

	public void setEmail(String value)
	{
		this.email = value;
	}

	public String getUrl()
	{
		return url;
	}

	public void setUrl(String value)
	{
		this.url = value;
	}

	public String getUrlname()
	{
		return urlname;
	}

	public void setUrlname(String value)
	{
		this.urlname = value;
	}

	public String getTime()
	{
		return time;
	}

	public void setTime(String value)
	{
		this.time = value;
	}

	public String getKeywords()
	{
		return keywords;
	}

	public void setKeywords(String value)
	{
		this.keywords = value;
	}

	public BoundsType getBounds()
	{
		return bounds;
	}

	public void setBounds(BoundsType value)
	{
		this.bounds = value;
	}

	public List<Gpx.Wpt> getWpt()
	{
		if (wpt == null)
		{
			wpt = new ArrayList<Gpx.Wpt>();
		}
		return this.wpt;
	}

	public List<Gpx.Rte> getRte()
	{
		if (rte == null)
		{
			rte = new ArrayList<Gpx.Rte>();
		}
		return this.rte;
	}

	public List<Gpx.Trk> getTrk()
	{
		if (trk == null)
		{
			trk = new ArrayList<Gpx.Trk>();
		}
		return this.trk;
	}

	public String getVersion()
	{
		if (version == null)
		{
			return "1.0";
		}
		else
		{
			return version;
		}
	}

	public void setVersion(String value)
	{
		this.version = value;
	}

	public String getCreator()
	{
		return creator;
	}

	public void setCreator(String value)
	{
		this.creator = value;
	}

	public static class Rte
	{

		protected String				name;
		protected String				cmt;
		protected String				desc;
		protected String				src;
		protected String				url;
		protected String				urlname;
		protected Integer			number;
		protected List<Gpx.Rte.Rtept>	rtept;

		public String getName()
		{
			return name;
		}

		public void setName(String value)
		{
			this.name = value;
		}

		public String getCmt()
		{
			return cmt;
		}

		public void setCmt(String value)
		{
			this.cmt = value;
		}

		public String getDesc()
		{
			return desc;
		}

		public void setDesc(String value)
		{
			this.desc = value;
		}

		public String getSrc()
		{
			return src;
		}

		public void setSrc(String value)
		{
			this.src = value;
		}

		public String getUrl()
		{
			return url;
		}

		public void setUrl(String value)
		{
			this.url = value;
		}

		public String getUrlname()
		{
			return urlname;
		}

		public void setUrlname(String value)
		{
			this.urlname = value;
		}

		public Integer getNumber()
		{
			return number;
		}

		public void setNumber(Integer value)
		{
			this.number = value;
		}

		public List<Gpx.Rte.Rtept> getRtept()
		{
			if (rtept == null)
			{
				rtept = new ArrayList<Gpx.Rte.Rtept>();
			}
			return this.rtept;
		}

		public static class Rtept
		{

			protected Double	ele;
			protected String	time;
			protected Double	magvar;
			protected Double	geoidheight;
			protected String		name;
			protected String		cmt;
			protected String		desc;
			protected String		src;
			protected String		url;
			protected String		urlname;
			protected String		sym;
			protected String		type;
			protected String		fix;
			protected Integer	sat;
			protected Double	hdop;
			protected Double	vdop;
			protected Double	pdop;
			protected Double	ageofdgpsdata;
			protected Integer		dgpsid;
			@Attribute(required = true)
			protected Double	lat;
			@Attribute(required = true)
			protected Double	lon;

			public Double getEle()
			{
				return ele;
			}

			public void setEle(Double value)
			{
				this.ele = value;
			}

			public String getTime()
			{
				return time;
			}

			public void setTime(String value)
			{
				this.time = value;
			}

			public Double getMagvar()
			{
				return magvar;
			}

			public void setMagvar(Double value)
			{
				this.magvar = value;
			}

			public Double getGeoidheight()
			{
				return geoidheight;
			}

			public void setGeoidheight(Double value)
			{
				this.geoidheight = value;
			}

			public String getName()
			{
				return name;
			}

			public void setName(String value)
			{
				this.name = value;
			}

			public String getCmt()
			{
				return cmt;
			}

			public void setCmt(String value)
			{
				this.cmt = value;
			}

			public String getDesc()
			{
				return desc;
			}

			public void setDesc(String value)
			{
				this.desc = value;
			}

			public String getSrc()
			{
				return src;
			}

			public void setSrc(String value)
			{
				this.src = value;
			}

			public String getUrl()
			{
				return url;
			}

			public void setUrl(String value)
			{
				this.url = value;
			}

			public String getUrlname()
			{
				return urlname;
			}

			public void setUrlname(String value)
			{
				this.urlname = value;
			}

			public String getSym()
			{
				return sym;
			}

			public void setSym(String value)
			{
				this.sym = value;
			}

			public String getType()
			{
				return type;
			}

			public void setType(String value)
			{
				this.type = value;
			}

			public String getFix()
			{
				return fix;
			}

			public void setFix(String value)
			{
				this.fix = value;
			}

			public Integer getSat()
			{
				return sat;
			}

			public void setSat(Integer value)
			{
				this.sat = value;
			}

			public Double getHdop()
			{
				return hdop;
			}

			public void setHdop(Double value)
			{
				this.hdop = value;
			}

			public Double getVdop()
			{
				return vdop;
			}

			public void setVdop(Double value)
			{
				this.vdop = value;
			}

			public Double getPdop()
			{
				return pdop;
			}

			public void setPdop(Double value)
			{
				this.pdop = value;
			}

			public Double getAgeofdgpsdata()
			{
				return ageofdgpsdata;
			}

			public void setAgeofdgpsdata(Double value)
			{
				this.ageofdgpsdata = value;
			}

			public Integer getDgpsid()
			{
				return dgpsid;
			}

			public void setDgpsid(Integer value)
			{
				this.dgpsid = value;
			}

			public Double getLat()
			{
				return lat;
			}

			public void setLat(Double value)
			{
				this.lat = value;
			}

			public Double getLon()
			{
				return lon;
			}

			public void setLon(Double value)
			{
				this.lon = value;
			}

		}

		@Override
		public String toString()
		{
			return "Rte [name=" + name + ", cmt=" + cmt + ", desc=" + desc + ", src=" + src + ", url=" + url + ", urlname="
					+ urlname + ", number=" + number + ", rtept=" + rtept + "]";
		}

	}

	public static class Trk
	{

	    @Element(required=false)
		protected String				name;
	    @Element(required=false)
        protected String				cmt;
	    @Element(required=false)
        protected String				desc;
	    @Element(required=false)
        protected String				src;
	    @Element(required=false)
        protected String				url;
	    @Element(required=false)
        protected String				urlname;
	    @Element(required=false)
        protected Integer			number;
		@ElementList(inline=true,required=false)
		protected List<Gpx.Trk.Trkseg>	trkseg;

		public String getName()
		{
			return name;
		}

		public void setName(String value)
		{
			this.name = value;
		}

		public String getCmt()
		{
			return cmt;
		}

		public void setCmt(String value)
		{
			this.cmt = value;
		}

		public String getDesc()
		{
			return desc;
		}

		public void setDesc(String value)
		{
			this.desc = value;
		}

		public String getSrc()
		{
			return src;
		}

		public void setSrc(String value)
		{
			this.src = value;
		}

		public String getUrl()
		{
			return url;
		}

		public void setUrl(String value)
		{
			this.url = value;
		}

		public String getUrlname()
		{
			return urlname;
		}

		public void setUrlname(String value)
		{
			this.urlname = value;
		}

		public Integer getNumber()
		{
			return number;
		}

		public void setNumber(Integer value)
		{
			this.number = value;
		}

		public List<Gpx.Trk.Trkseg> getTrkseg()
		{
			if (trkseg == null)
			{
				trkseg = new ArrayList<Gpx.Trk.Trkseg>();
			}
			return this.trkseg;
		}

		public static class Trkseg
		{

		    @ElementList(inline=true)
			protected List<Gpx.Trk.Trkseg.Trkpt>	trkpt;

			public List<Gpx.Trk.Trkseg.Trkpt> getTrkpt()
			{
				if (trkpt == null)
				{
					trkpt = new ArrayList<Gpx.Trk.Trkseg.Trkpt>();
				}
				return this.trkpt;
			}

			public static class Trkpt
			{

			    @Element(required=false)
				protected Double	ele;
			    @Element(required=false)
                protected String			time;
			    @Element(required=false)
                protected Float	course;
			    @Element(required=false)
                protected Float	speed;
			    @Element(required=false)
                protected Double	magvar;
			    @Element(required=false)
                protected Double	geoidheight;
			    @Element(required=false)
                protected String		name;
			    @Element(required=false)
                protected String		cmt;
			    @Element(required=false)
                protected String		desc;
			    @Element(required=false)
                protected String		src;
			    @Element(required=false)
                protected String		url;
			    @Element(required=false)
                protected String		urlname;
			    @Element(required=false)
                protected String		sym;
			    @Element(required=false)
                protected String		type;
			    @Element(required=false)
                protected String		fix;
			    @Element(required=false)
                protected Integer	sat;
			    @Element(required=false)
                protected Double	hdop;
			    @Element(required=false)
                protected Double	vdop;
			    @Element(required=false)
                protected Double	pdop;
			    @Element(required=false)
                protected Double	ageofdgpsdata;
			    @Element(required=false)
                protected Integer		dgpsid;
				@Attribute(required = true)
				protected Double	lat;
				@Attribute(required = true)
				protected Double	lon;

				public Double getEle()
				{
					return ele;
				}

				public void setEle(Double value)
				{
					this.ele = value;
				}

				public String getTime()
				{
					return time;
				}

				public void setTime(String dateTimeString)
				{
					this.time = dateTimeString;
				}

				public Float getCourse()
				{
					return course;
				}

				public void setCourse(Float f)
				{
					this.course = f;
				}

				public Float getSpeed()
				{
					return speed;
				}

				public void setSpeed(Float f)
				{
					this.speed = f;
				}

				public Double getMagvar()
				{
					return magvar;
				}

				public void setMagvar(Double value)
				{
					this.magvar = value;
				}

				public Double getGeoidheight()
				{
					return geoidheight;
				}

				public void setGeoidheight(Double value)
				{
					this.geoidheight = value;
				}

				public String getName()
				{
					return name;
				}

				public void setName(String value)
				{
					this.name = value;
				}

				public String getCmt()
				{
					return cmt;
				}

				public void setCmt(String value)
				{
					this.cmt = value;
				}

				public String getDesc()
				{
					return desc;
				}

				public void setDesc(String value)
				{
					this.desc = value;
				}

				public String getSrc()
				{
					return src;
				}

				public void setSrc(String value)
				{
					this.src = value;
				}

				public String getUrl()
				{
					return url;
				}

				public void setUrl(String value)
				{
					this.url = value;
				}

				public String getUrlname()
				{
					return urlname;
				}

				public void setUrlname(String value)
				{
					this.urlname = value;
				}

				public String getSym()
				{
					return sym;
				}

				public void setSym(String value)
				{
					this.sym = value;
				}

				public String getType()
				{
					return type;
				}

				public void setType(String value)
				{
					this.type = value;
				}

				public String getFix()
				{
					return fix;
				}

				public void setFix(String value)
				{
					this.fix = value;
				}

				public Integer getSat()
				{
					return sat;
				}

				public void setSat(Integer value)
				{
					this.sat = value;
				}

				public Double getHdop()
				{
					return hdop;
				}

				public void setHdop(Double value)
				{
					this.hdop = value;
				}

				public Double getVdop()
				{
					return vdop;
				}

				public void setVdop(Double value)
				{
					this.vdop = value;
				}

				public Double getPdop()
				{
					return pdop;
				}

				public void setPdop(Double value)
				{
					this.pdop = value;
				}

				public Double getAgeofdgpsdata()
				{
					return ageofdgpsdata;
				}

				public void setAgeofdgpsdata(Double value)
				{
					this.ageofdgpsdata = value;
				}

				public Integer getDgpsid()
				{
					return dgpsid;
				}

				public void setDgpsid(Integer value)
				{
					this.dgpsid = value;
				}

				public Double getLat()
				{
					return lat;
				}

				public void setLat(Double value)
				{
					this.lat = value;
				}

				public Double getLon()
				{
					return lon;
				}

				public void setLon(Double value)
				{
					this.lon = value;
				}

				@Override
				public String toString()
				{
					return "Trkpt [ele=" + ele + ", time=" + time + ", course=" + course + ", speed=" + speed + ", magvar="
							+ magvar + ", geoidheight=" + geoidheight + ", name=" + name + ", cmt=" + cmt + ", desc=" + desc
							+ ", src=" + src + ", url=" + url + ", urlname=" + urlname + ", sym=" + sym + ", type=" + type
							+ ", fix=" + fix + ", sat=" + sat + ", hdop=" + hdop + ", vdop=" + vdop + ", pdop=" + pdop
							+ ", ageofdgpsdata=" + ageofdgpsdata + ", dgpsid=" + dgpsid + ", lat=" + lat + ", lon=" + lon + "]";
				}

			}

			@Override
			public String toString()
			{
				return "Trkseg [trkpt=" + trkpt + "]";
			}

		}

		@Override
		public String toString()
		{
			return "Trk [name=" + name + ", cmt=" + cmt + ", desc=" + desc + ", src=" + src + ", url=" + url + ", urlname="
					+ urlname + ", number=" + number + ", trkseg=" + trkseg + "]";
		}

	}

	public static class Wpt
	{

		protected Double	ele;
		protected String	time;
		protected Double	magvar;
		protected Double	geoidheight;
		protected String		name;
		protected String		cmt;
		protected String		desc;
		protected String		src;
		protected String		url;
		protected String		urlname;
		protected String		sym;
		protected String		type;
		protected String		fix;
		protected Integer	sat;
		protected Double	hdop;
		protected Double	vdop;
		protected Double	pdop;
		protected Double	ageofdgpsdata;
		protected Integer		dgpsid;
		@Attribute(required = true)
		protected Double	lat;
		@Attribute(required = true)
		protected Double	lon;

		public Double getEle()
		{
			return ele;
		}

		public void setEle(Double value)
		{
			this.ele = value;
		}

		public String getTime()
		{
			return time;
		}

		public void setTime(String value)
		{
			this.time = value;
		}

		public Double getMagvar()
		{
			return magvar;
		}

		public void setMagvar(Double value)
		{
			this.magvar = value;
		}

		public Double getGeoidheight()
		{
			return geoidheight;
		}

		public void setGeoidheight(Double value)
		{
			this.geoidheight = value;
		}

		public String getName()
		{
			return name;
		}

		public void setName(String value)
		{
			this.name = value;
		}

		public String getCmt()
		{
			return cmt;
		}

		public void setCmt(String value)
		{
			this.cmt = value;
		}

		public String getDesc()
		{
			return desc;
		}

		public void setDesc(String value)
		{
			this.desc = value;
		}

		public String getSrc()
		{
			return src;
		}

		public void setSrc(String value)
		{
			this.src = value;
		}

		public String getUrl()
		{
			return url;
		}

		public void setUrl(String value)
		{
			this.url = value;
		}

		public String getUrlname()
		{
			return urlname;
		}

		public void setUrlname(String value)
		{
			this.urlname = value;
		}

		public String getSym()
		{
			return sym;
		}

		public void setSym(String value)
		{
			this.sym = value;
		}

		public String getType()
		{
			return type;
		}

		public void setType(String value)
		{
			this.type = value;
		}

		public String getFix()
		{
			return fix;
		}

		public void setFix(String value)
		{
			this.fix = value;
		}

		public Integer getSat()
		{
			return sat;
		}

		public void setSat(Integer value)
		{
			this.sat = value;
		}

		public Double getHdop()
		{
			return hdop;
		}

		public void setHdop(Double value)
		{
			this.hdop = value;
		}

		public Double getVdop()
		{
			return vdop;
		}

		public void setVdop(Double value)
		{
			this.vdop = value;
		}

		public Double getPdop()
		{
			return pdop;
		}

		public void setPdop(Double value)
		{
			this.pdop = value;
		}

		public Double getAgeofdgpsdata()
		{
			return ageofdgpsdata;
		}

		public void setAgeofdgpsdata(Double value)
		{
			this.ageofdgpsdata = value;
		}

		public Integer getDgpsid()
		{
			return dgpsid;
		}

		public void setDgpsid(Integer value)
		{
			this.dgpsid = value;
		}

		public Double getLat()
		{
			return lat;
		}

		public void setLat(Double value)
		{
			this.lat = value;
		}

		public Double getLon()
		{
			return lon;
		}

		public void setLon(Double value)
		{
			this.lon = value;
		}

		@Override
		public String toString()
		{
			return "Wpt [ele=" + ele + ", time=" + time + ", magvar=" + magvar + ", geoidheight=" + geoidheight + ", name=" + name
					+ ", cmt=" + cmt + ", desc=" + desc + ", src=" + src + ", url=" + url + ", urlname=" + urlname + ", sym=" + sym
					+ ", type=" + type + ", fix=" + fix + ", sat=" + sat + ", hdop=" + hdop + ", vdop=" + vdop + ", pdop=" + pdop
					+ ", ageofdgpsdata=" + ageofdgpsdata + ", dgpsid=" + dgpsid + ", lat=" + lat + ", lon=" + lon + "]";
		}

	}

	@Override
	public String toString()
	{
		return "Gpx [name=" + name + ", desc=" + desc + ", author=" + author + ", email=" + email + ", url=" + url + ", urlname="
				+ urlname + ", time=" + time + ", keywords=" + keywords + ", bounds=" + bounds + ", wpt=" + wpt + ", rte=" + rte
				+ ", trk=" + trk + ", version=" + version + ", creator=" + creator + "]";
	}

}
